language: haskell

install:
    - cabal install yesod-platform yesod-bin --max-backjumps=-1 --reorder-goals
    - cabal install --enable-tests . yesod-platform yesod-bin --max-backjumps=-1 --reorder-goals
script:
    - yesod test
