language: haskell
ghc: 7.6

install:
    - cabal install --force-reinstalls $(grep "yesod-platform\s*==" *.cabal | tr --delete ", ")
    - cabal install --only-dependencies
    - cabal install
script:
    - yesod test
